# Generated by Django 4.2.13 on 2024-07-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updates_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updates_on',
            new_name='updated_on',
        ),
    ]
